name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Core tests without LLM providers
  core-tests:
    name: Core Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.11
      - name: Install the project
        run: uv sync --all-extras
      - name: Run core tests
        run: uv run pytest tests/ -k 'not llm and not openai and not gemini and not anthropic and not cohere and not vertexai and not mistral and not xai and not docs'
        env:
          INSTRUCTOR_ENV: CI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}

  # Provider tests run in parallel
  provider-tests:
    name: ${{ matrix.provider.name }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          - name: Openai
            env_key: OPENAI_API_KEY
            test_path: tests/llm/test_openai
          - name: Anthropic
            env_key: ANTHROPIC_API_KEY
            test_path: tests/llm/test_anthropic
          - name: Gemini
            env_key: GOOGLE_API_KEY
            test_path: tests/llm/test_gemini
          - name: Google GenAI
            env_key: GOOGLE_API_KEY
            test_path: tests/llm/test_genai
          - name: Cohere
            env_key: COHERE_API_KEY
            test_path: tests/llm/test_cohere
          - name: XAI
            env_key: XAI_API_KEY
            test_path: tests/llm/test_xai

    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.11
      - name: Install the project
        run: uv sync --all-extras
      - name: Run ${{ matrix.provider.name }} tests
        run: uv run pytest ${{ matrix.provider.test_path }} -n auto
        env:
          INSTRUCTOR_ENV: CI
          ${{ matrix.provider.env_key }}: ${{ secrets[matrix.provider.env_key] }}

  # Auto client needs multiple providers
  auto-client-test:
    name: Auto Client Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.11
      - name: Install the project
        run: uv sync --all-extras
      - name: Run Auto Client tests
        run: uv run pytest tests/test_auto_client.py
        env:
          INSTRUCTOR_ENV: CI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
